version: 2
updates:
  # Enable version updates for npm (JavaScript/Node.js)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "geekatwork"
    assignees:
      - "geekatwork"
    commit-message:
      prefix: "npm"
      include: "scope"
    labels:
      - "dependencies"
      - "npm"
    
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 3
    reviewers:
      - "geekatwork"
    assignees:
      - "geekatwork"
    commit-message:
      prefix: "docker"
    labels:
      - "dependencies"
      - "docker"

  # Enable version updates for GitHub Actions (if you add workflows later)
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:00"
    open-pull-requests-limit: 2
    reviewers:
      - "geekatwork"
    assignees:
      - "geekatwork"
    commit-message:
      prefix: "actions"
    labels:
      - "dependencies"
      - "github-actions"
