version: '3.8'

services:
  nz-mashup:
    build: .
    ports:
      - "5173:5173"
    volumes:
      # Mount source code for development (hot reload)
      - ./src:/app/src
      - ./public:/app/public
      - ./data:/app/data
      - ./index.html:/app/index.html
      - ./vite.config.js:/app/vite.config.js
      # Prevent node_modules from being overwritten
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - COSMOS_DB_ENDPOINT=https://localhost:8081
      - COSMOS_DB_KEY=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
    depends_on:
      - cosmosdb
    stdin_open: true
    tty: true

  # Azure Cosmos DB Emulator for local development
  cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    ports:
      - "8081:8081"      # Cosmos DB HTTPS endpoint
      - "10251:10251"    # MongoDB endpoint
      - "10252:10252"    # Cassandra endpoint  
      - "10253:10253"    # Table API endpoint
      - "10254:10254"    # Gremlin endpoint
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
      - AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=127.0.0.1
      - AZURE_COSMOS_EMULATOR_ENABLE_MONGODB_ENDPOINT=true
    volumes:
      - cosmos-data:/tmp/cosmos/appdata

volumes:
  cosmos-data:
